emv_profiles:
  - profile_id: "IRAN_DEBIT_STANDARD_V1"
    aid: "A0000002480200"
    application_label: "IRAN DEBIT"
    currency_code: "364"
    country_code: "IR"
    language_code: "FA"
    card_holder_verification_method: "PIN"
    terminal_risk_management: "ONLINE"
    issuer_action_code_default: "0000000000"
    issuer_action_code_denial: "0000000000"
    issuer_action_code_online: "0000000000"
    
  - profile_id: "IRAN_CREDIT_STANDARD_V1"
    aid: "A0000002480201"
    application_label: "IRAN CREDIT"
    currency_code: "364"
    country_code: "IR"
    language_code: "FA"
    card_holder_verification_method: "PIN"
    terminal_risk_management: "ONLINE"
    issuer_action_code_default: "0000000000"
    issuer_action_code_denial: "0000000000"
    issuer_action_code_online: "0000000000"
    
  - profile_id: "IRAN_BUSINESS_STANDARD_V1"
    aid: "A0000002480202"
    application_label: "IRAN BUSINESS"
    currency_code: "364"
    country_code: "IR"
    language_code: "FA"
    card_holder_verification_method: "PIN"
    terminal_risk_management: "ONLINE"
    issuer_action_code_default: "0000000000"
    issuer_action_code_denial: "0000000000"
    issuer_action_code_online: "0000000000"